---
- name: Generate hosts file in localhost for all ucloud hosts
  hosts: localhost
  tasks:
    - name: Copy hosts file
      command: cp /etc/hosts hosts
    - name: Update uhosts IPs in hosts file
      lineinfile:
        dest: hosts
        regexp: "^{{ hostvars[item].ucloud.PublicIP | replace('.', '\\.') }}"
        line: "{{ hostvars[item].ucloud.PublicIP }} {{ item }}.ucloud"
      with_items: groups.uhosts
    - debug: msg="Copy hosts to overwrite your /etc/hosts"
- name: Generate hosts file in all ucloud hosts
  hosts: uhosts
  sudo: true
  tasks:
    - name: Update uhosts IPs in hosts file
      lineinfile:
        dest: /etc/hosts
        regexp: "^{{ hostvars[item].ucloud.PublicIP | replace('.', '\\.') }}"
        line: "{{ hostvars[item].ucloud.PublicIP }} {{ item }}.ucloud"
      with_items: groups.uhosts
    - name: Update uhosts private IPs in hosts file
      lineinfile:
        dest: /etc/hosts
        regexp: "^{{ hostvars[item].ucloud.PrivateIP | replace('.', '\\.') }}"
        line: "{{ hostvars[item].ucloud.PrivateIP }} {{ item }}.private"
      with_items: groups.uhosts
